# Mercantile Trading Bot Configuration

database:
  path: "./marketmaestro.db"

api:
  port: 8080
  timeout: 30s

ui:
  port: 8081

logging:
  level: "info"

# Exchange configurations
exchanges:
  bybit:
    enabled: true
    pairs:
      - symbol: "BTCUSDT"
        strategies:
          - name: "simple_sma"
            config:
              short_period: 10
              long_period: 20
              position_size: 0.01
              interval: "1m"  # 1-minute candles for fast SMA signals
          - name: "rsi_strategy"
            config:
              period: 14
              oversold: 30
              overbought: 70
              position_size: 0.005
              interval: "15m"  # 15-minute candles for RSI analysis
      - symbol: "ADAUSDT"
        strategies:
          - name: "super_trend"
            config:
              position_size: 0.005
              interval: "15m"  # 15-minute candles for RSI analysis
      - symbol: "ETHUSDT"
        strategies:
          - name: "simple_sma"
            config:
              short_period: 5
              long_period: 15
              position_size: 0.1
              interval: "5m"  # 5-minute candles for ETH trading
  
  bitvavo:
    enabled: false
    pairs:
      - symbol: "BTC-EUR"
        strategies:
          - name: "simple_sma"
            config:
              short_period: 12
              long_period: 26
              position_size: 0.01

# Global strategy settings
strategies:
  directory: "./strategies"
  default_interval: "1m"
  max_concurrent: 10
